<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClinicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('clinics')->insert([
            [
                'clinic_name' => 'HEALTHFIRST MEDICAL CENTER',
                'registered_name' => 'HEALTHFIRST MEDICAL AND DIAGNOSTIC CLINIC INC.',
                'ptr_no' => 'PTR-1001',
                'ptr_date_issued' => '2024-01-10',
                'other_hmo_accreditation' => 'MAXICARE, INTELLICARE',
                'tax_identification_no' => '123-456-789',
                'tax_type' => 'VAT',
                'business_type' => 'CORPORATION',
                'vat_type' => 'VAT 12%',
                'withholding_tax' => 'ZERO',
                'update_info_1903' => 'CHANGE IN BUSINESS NAME',
                'is_branch' => false,
                'sec_registration_no' => 'SEC-2024-001',
                'complete_address' => '123 HEALTH ST., MAKATI CITY',
                'clinic_landline' => '02-8876-1234',
                'clinic_mobile' => '09171234567',
                'viber_no' => '09171234567',
                'clinic_email' => 'INFO@HEALTHFIRST.COM',
                'alt_address' => 'UNIT 2B WELLNESS TOWER, MAKATI',
                'clinic_staff_name' => 'MARIA SANTOS',
                'clinic_staff_mobile' => '09181234567',
                'clinic_staff_viber' => '09181234567',
                'clinic_staff_email' => 'MARIA@HEALTHFIRST.COM',
                'bank_account_name' => 'HEALTHFIRST MEDICAL CENTER',
                'bank_account_number' => '1234567890',
                'bank_name' => 'BPI',
                'bank_branch' => 'MAKATI MAIN',
                'account_type' => 'SAVINGS',
                'accreditation_status' => 'ACTIVE',
            ],
            [
                'clinic_name' => 'CAREPOINT CLINIC',
                'registered_name' => 'CAREPOINT DIAGNOSTIC SERVICES',
                'ptr_no' => 'PTR-1002',
                'ptr_date_issued' => '2023-12-15',
                'other_hmo_accreditation' => 'PHILCARE, MEDICARD',
                'tax_identification_no' => '987-654-321',
                'tax_type' => 'NON-VAT',
                'business_type' => 'SOLE PROPRIETORSHIP',
                'vat_type' => 'NON-VAT',
                'withholding_tax' => 'ZERO',
                'update_info_1903' => 'CHANGE IN ADDRESS',
                'is_branch' => false,
                'sec_registration_no' => 'SEC-2023-045',
                'complete_address' => '456 WELLNESS AVE., QUEZON CITY',
                'clinic_landline' => '02-8899-2233',
                'clinic_mobile' => '09281234567',
                'viber_no' => '09281234567',
                'clinic_email' => 'CONTACT@CAREPOINT.COM',
                'alt_address' => null,
                'clinic_staff_name' => 'JUAN DELA CRUZ',
                'clinic_staff_mobile' => '09391234567',
                'clinic_staff_viber' => '09391234567',
                'clinic_staff_email' => 'JUAN@CAREPOINT.COM',
                'bank_account_name' => 'CAREPOINT CLINIC',
                'bank_account_number' => '9876543210',
                'bank_name' => 'METROBANK',
                'bank_branch' => 'QC CENTRAL',
                'account_type' => 'SAVINGS',
                'accreditation_status' => 'ACTIVE',
            ],
            [
                'clinic_name' => 'MEDEASE DIAGNOSTIC CENTER',
                'registered_name' => 'MEDEASE DIAGNOSTICS CO.',
                'ptr_no' => 'PTR-1003',
                'ptr_date_issued' => '2024-02-20',
                'other_hmo_accreditation' => 'MAXICARE, PHILCARE',
                'tax_identification_no' => '321-654-987',
                'tax_type' => 'NON-VAT',
                'business_type' => 'PARTNERSHIP',
                'vat_type' => 'NON-VAT',
                'withholding_tax' => '2%',
                'update_info_1903' => 'CHANGE IN TAX TYPE',
                'is_branch' => false,
                'sec_registration_no' => 'SEC-2022-222',
                'complete_address' => '789 RECOVERY ROAD, PASIG CITY',
                'clinic_landline' => '02-7755-4433',
                'clinic_mobile' => '09191234567',
                'viber_no' => '09191234567',
                'clinic_email' => 'HELLO@MEDEASE.COM',
                'alt_address' => 'UNIT 5B LIFELINE BLDG., PASIG',
                'clinic_staff_name' => 'LIZA CRUZ',
                'clinic_staff_mobile' => '09561234567',
                'clinic_staff_viber' => '09561234567',
                'clinic_staff_email' => 'LIZA@MEDEASE.COM',
                'bank_account_name' => 'MEDEASE DIAGNOSTIC CENTER',
                'bank_account_number' => '1357913579',
                'bank_name' => 'UNIONBANK',
                'bank_branch' => 'ORTIGAS',
                'account_type' => 'CURRENT',
                'accreditation_status' => 'SPECIFIC ACCOUNT',
            ],
            [
                'clinic_name' => 'TOTALCARE MEDICAL HUB',
                'registered_name' => 'TOTALCARE MEDICAL SERVICES INC.',
                'ptr_no' => 'PTR-1004',
                'ptr_date_issued' => '2024-05-05',
                'other_hmo_accreditation' => 'INTELLICARE, MEDICARD',
                'tax_identification_no' => '555-444-333',
                'tax_type' => 'VAT',
                'business_type' => 'CORPORATION',
                'vat_type' => 'VAT 12%',
                'withholding_tax' => 'ZERO',
                'update_info_1903' => 'CHANGE IN BUSINESS NAME',
                'is_branch' => false,
                'sec_registration_no' => 'SEC-2021-654',
                'complete_address' => '25 MEDICAL LANE, TAGUIG CITY',
                'clinic_landline' => '02-8890-7766',
                'clinic_mobile' => '09174561234',
                'viber_no' => '09174561234',
                'clinic_email' => 'ADMIN@TOTALCARE.COM',
                'alt_address' => null,
                'clinic_staff_name' => 'CARLO REYES',
                'clinic_staff_mobile' => '09274561234',
                'clinic_staff_viber' => '09274561234',
                'clinic_staff_email' => 'CARLO@TOTALCARE.COM',
                'bank_account_name' => 'TOTALCARE MEDICAL HUB',
                'bank_account_number' => '2468246824',
                'bank_name' => 'BDO',
                'bank_branch' => 'TAGUIG CITY',
                'account_type' => 'SAVINGS',
                'accreditation_status' => 'ACTIVE',
            ],
            [
                'clinic_name' => 'PRIMEHEALTH FAMILY CLINIC',
                'registered_name' => 'PRIMEHEALTH FAMILY CLINIC AND LABORATORY',
                'ptr_no' => 'PTR-1005',
                'ptr_date_issued' => '2023-11-25',
                'other_hmo_accreditation' => 'PHILCARE',
                'tax_identification_no' => '888-777-666',
                'tax_type' => '0%',
                'business_type' => 'SOLE PROPRIETORSHIP',
                'vat_type' => 'NON-VAT',
                'withholding_tax' => '5%',
                'update_info_1903' => 'CHANGE IN ADDRESS',
                'is_branch' => false,
                'sec_registration_no' => 'SEC-2023-987',
                'complete_address' => '9 EVERGREEN ST., LAS PIÑAS CITY',
                'clinic_landline' => '02-8787-5678',
                'clinic_mobile' => '09981234567',
                'viber_no' => '09981234567',
                'clinic_email' => 'PRIME@HEALTHCLINIC.COM',
                'alt_address' => null,
                'clinic_staff_name' => 'ANGELA RAMOS',
                'clinic_staff_mobile' => '09181234568',
                'clinic_staff_viber' => '09181234568',
                'clinic_staff_email' => 'ANGELA@PRIMEHEALTH.COM',
                'bank_account_name' => 'PRIMEHEALTH FAMILY CLINIC',
                'bank_account_number' => '3692581470',
                'bank_name' => 'LANDBANK',
                'bank_branch' => 'LAS PIÑAS',
                'account_type' => 'CURRENT',
                'accreditation_status' => 'SILENT',
            ],
        ]);
    }
}
