<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClinicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('clinics')->insert([
            [
                'clinic_name' => 'HealthFirst Medical Center',
                'registered_name' => 'HealthFirst Medical and Diagnostic Clinic Inc.',
                'ptr_no' => 'PTR-1001',
                'ptr_date_issued' => '2024-01-10',
                'other_hmo_accreditation' => 'Maxicare, Intellicare',
                'tax_identification_no' => '123-456-789',
                'tax_type' => 'VAT',
                'business_type' => 'CORPORATION',
                'sec_registration_no' => 'SEC-2024-001',
                'clinic_address' => '123 Health St., Makati City',
                'clinic_landline' => '02-8876-1234',
                'clinic_mobile' => '09171234567',
                'viber_no' => '09171234567',
                'clinic_email' => 'info@healthfirst.com',
                'alt_address' => 'Unit 2B Wellness Tower, Makati',
                'clinic_staff_name' => 'Maria Santos',
                'clinic_staff_mobile' => '09181234567',
                'clinic_staff_viber' => '09181234567',
                'clinic_staff_email' => 'maria@healthfirst.com',
                'bank_account_name' => 'HealthFirst Medical Center',
                'bank_account_number' => '1234567890',
                'bank_name' => 'BPI',
                'bank_branch' => 'Makati Main',
                'account_type' => 'SAVINGS',
                'accreditation_status' => 'ACTIVE',
            ],
            [
                'clinic_name' => 'CarePoint Clinic',
                'registered_name' => 'CarePoint Diagnostic Services',
                'ptr_no' => 'PTR-1002',
                'ptr_date_issued' => '2023-12-15',
                'other_hmo_accreditation' => 'PhilCare, Medicard',
                'tax_identification_no' => '987-654-321',
                'tax_type' => 'NON-VAT',
                'business_type' => 'SOLE PROPRIETOR',
                'sec_registration_no' => 'SEC-2023-045',
                'clinic_address' => '456 Wellness Ave., Quezon City',
                'clinic_landline' => '02-8899-2233',
                'clinic_mobile' => '09281234567',
                'viber_no' => '09281234567',
                'clinic_email' => 'contact@carepoint.com',
                'alt_address' => null,
                'clinic_staff_name' => 'Juan Dela Cruz',
                'clinic_staff_mobile' => '09391234567',
                'clinic_staff_viber' => '09391234567',
                'clinic_staff_email' => 'juan@carepoint.com',
                'bank_account_name' => 'CarePoint Clinic',
                'bank_account_number' => '9876543210',
                'bank_name' => 'Metrobank',
                'bank_branch' => 'QC Central',
                'account_type' => 'SAVINGS',
                'accreditation_status' => 'ACTIVE',
            ],
            [
                'clinic_name' => 'MedEase Diagnostic Center',
                'registered_name' => 'MedEase Diagnostics Co.',
                'ptr_no' => 'PTR-1003',
                'ptr_date_issued' => '2024-02-20',
                'other_hmo_accreditation' => 'Maxicare, PhilCare',
                'tax_identification_no' => '321-654-987',
                'tax_type' => 'NON-VAT',
                'business_type' => 'PARTNERSHIP',
                'sec_registration_no' => 'SEC-2022-222',
                'clinic_address' => '789 Recovery Road, Pasig City',
                'clinic_landline' => '02-7755-4433',
                'clinic_mobile' => '09191234567',
                'viber_no' => '09191234567',
                'clinic_email' => 'hello@medease.com',
                'alt_address' => 'Unit 5B Lifeline Bldg., Pasig',
                'clinic_staff_name' => 'Liza Cruz',
                'clinic_staff_mobile' => '09561234567',
                'clinic_staff_viber' => '09561234567',
                'clinic_staff_email' => 'liza@medease.com',
                'bank_account_name' => 'MedEase Diagnostic Center',
                'bank_account_number' => '1357913579',
                'bank_name' => 'UnionBank',
                'bank_branch' => 'Ortigas',
                'account_type' => 'CURRENT',
                'accreditation_status' => 'SPECIFIC ACCOUNT',
            ],
            [
                'clinic_name' => 'TotalCare Medical Hub',
                'registered_name' => 'TotalCare Medical Services Inc.',
                'ptr_no' => 'PTR-1004',
                'ptr_date_issued' => '2024-05-05',
                'other_hmo_accreditation' => 'Intellicare, Medicard',
                'tax_identification_no' => '555-444-333',
                'tax_type' => 'VAT',
                'business_type' => 'CORPORATION',
                'sec_registration_no' => 'SEC-2021-654',
                'clinic_address' => '25 Medical Lane, Taguig City',
                'clinic_landline' => '02-8890-7766',
                'clinic_mobile' => '09174561234',
                'viber_no' => '09174561234',
                'clinic_email' => 'admin@totalcare.com',
                'alt_address' => null,
                'clinic_staff_name' => 'Carlo Reyes',
                'clinic_staff_mobile' => '09274561234',
                'clinic_staff_viber' => '09274561234',
                'clinic_staff_email' => 'carlo@totalcare.com',
                'bank_account_name' => 'TotalCare Medical Hub',
                'bank_account_number' => '2468246824',
                'bank_name' => 'BDO',
                'bank_branch' => 'Taguig City',
                'account_type' => 'SAVINGS',
                'accreditation_status' => 'ACTIVE',
            ],
            [
                'clinic_name' => 'PrimeHealth Family Clinic',
                'registered_name' => 'PrimeHealth Family Clinic and Laboratory',
                'ptr_no' => 'PTR-1005',
                'ptr_date_issued' => '2023-11-25',
                'other_hmo_accreditation' => 'PhilCare',
                'tax_identification_no' => '888-777-666',
                'tax_type' => '0%',
                'business_type' => 'SOLE PROPRIETOR',
                'sec_registration_no' => 'SEC-2023-987',
                'clinic_address' => '9 Evergreen St., Las Piñas City',
                'clinic_landline' => '02-8787-5678',
                'clinic_mobile' => '09981234567',
                'viber_no' => '09981234567',
                'clinic_email' => 'prime@healthclinic.com',
                'alt_address' => null,
                'clinic_staff_name' => 'Angela Ramos',
                'clinic_staff_mobile' => '09181234568',
                'clinic_staff_viber' => '09181234568',
                'clinic_staff_email' => 'angela@primehealth.com',
                'bank_account_name' => 'PrimeHealth Family Clinic',
                'bank_account_number' => '3692581470',
                'bank_name' => 'Landbank',
                'bank_branch' => 'Las Piñas',
                'account_type' => 'CURRENT',
                'accreditation_status' => 'SILENT',
            ],
        ]);
    }
}
