<?php

namespace App\Filament\Resources;

use App\Filament\Resources\GeneratedSoaResource\Pages;
use App\Models\GeneratedSoa;
use App\Models\Role;
use App\Services\PrinterService;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Resources\Resource;
use Filament\Tables\Actions\Action;
use Barryvdh\DomPDF\Facade\Pdf;
use Filament\Infolists\Components\Grid;
use Filament\Tables\Columns\TextColumn;
use Illuminate\Support\Facades\Storage;
use Filament\Notifications\Notification;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class GeneratedSoaResource extends Resource
{
    protected static ?string $model = GeneratedSoa::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';
    protected static ?string $navigationGroup = 'Claims Management';
    protected static ?string $label = 'Generated ADC';


    // ✅ Table schema
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('id')
                    ->label('ADC ID')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('clinic.clinic_name')
                    ->label('Clinic')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('from_date')->label('From')->date(),
                Tables\Columns\TextColumn::make('to_date')->label('To')->date(),
                Tables\Columns\TextColumn::make('total_amount')->label('Total')->money('php'),
                Tables\Columns\TextColumn::make('status')
                    ->label('Status')
                    ->badge()
                    ->searchable(),
                Tables\Columns\TextColumn::make('generatedBy.name')->label('Generated by'),
                Tables\Columns\TextColumn::make('created_at')->label('Generated At')->dateTime(),
                Tables\Columns\TextColumn::make('generatedBy.name')
                    ->label('Generated by')
                    ->searchable(),

                Tables\Columns\TextColumn::make('created_at')
                    ->label('Generated At')
                    ->dateTime()
                    ->sortable(),

                Tables\Columns\TextColumn::make('print_count')
                    ->label('Print Count'),

                Tables\Columns\BadgeColumn::make('request_status')
                    ->label('Original Request')
                    ->getStateUsing(fn($record) => $record->request_status ?? 'Not Requested')
                    ->colors([
                        'warning' => 'PENDING',
                        'success' => 'APPROVED',
                        'danger' => 'REJECTED',
                        'secondary' => 'Not Requested',
                    ])
            ])
            ->actions([

                // Request Original
                Action::make('request_original')
                    ->label('Request Original')
                    ->visible(auth()->user()->can('generated_adc.request'))
                    ->icon('heroicon-o-paper-airplane')
                    ->color('warning')
                    ->requiresConfirmation()
                    ->modalHeading('Request Original ADC')
                    ->modalDescription('Are you sure you want to request the original ADC? This will notify management for approval.')
                    ->modalSubmitActionLabel('Yes, Request')
                    ->action(function (GeneratedSoa $record) {
                        if ($record->request_status === 'PENDING' || $record->request_status === 'APPROVED') {
                            Notification::make()
                                ->title('Already requested or approved')
                                ->body('You cannot request again.')
                                ->warning()
                                ->send();
                            return;
                        }

                        $record->update([
                            'is_request_original' => true,
                            'request_status' => 'PENDING',
                        ]);

                        Notification::make()
                            ->title('Request sent')
                            ->body('Your request for the original ADC has been submitted.')
                            ->success()
                            ->send();
                    })
                    ->visible(fn(GeneratedSoa $record) => $record->request_status === null),

                // Approve Original (Admin only)
                Action::make('approve_original')
                    ->label('Approve Original')
                    ->visible(auth()->user()->can('generated_adc.approve'))
                    ->icon('heroicon-o-check-circle')
                    ->color('success')
                    ->requiresConfirmation()
                    ->modalHeading('Approve Original ADC')
                    ->modalDescription('This request has been approved. The Claims Management team can now print the original ADC. Note: This action is allowed only once.')
                    ->modalSubmitActionLabel('Yes, Approve')
                    ->action(function (GeneratedSoa $record) {
                        $record->update([
                            'request_status' => 'APPROVED',
                        ]);

                        Notification::make()
                            ->title('Approved')
                            ->body('Original ADC request has been approved.')
                            ->success()
                            ->send();
                    })
                    ->visible(fn(GeneratedSoa $record) => $record->request_status === 'PENDING' && auth()->user()->can('generated_adc.approve')),

                // Download Original (user only after approval)
                Action::make('print_original')
                    ->label('Print Original ADC')
                    ->icon('heroicon-o-printer')
                    ->button()
                    ->action(function (GeneratedSoa $record) {
                        $disk = Storage::disk('public');

                        // Ensure the request is approved
                        if ($record->request_status !== 'APPROVED') {
                            Notification::make()
                                ->title('Not allowed')
                                ->body('You cannot print the original ADC yet. Request must be approved first.')
                                ->warning()
                                ->send();
                            return;
                        }

                        // Check if file exists
                        if (!$disk->exists($record->file_path)) {
                            Notification::make()
                                ->title('PDF not found')
                                ->body('Original ADC PDF file is missing.')
                                ->warning()
                                ->send();
                            return;
                        }

                        // Attempt to print
                        $clinicPrinter = $record->clinic->printer_name ?? null; // Make sure $record->clinic relationship exists
                        $printerName = PrinterService::getPrinter($clinicPrinter);
                        $absoluteOriginalPath = $disk->path($record->file_path);

                        if ($printerName) {
                            exec(
                                'lp -o landscape -d ' . escapeshellarg($printerName) . ' ' . escapeshellarg($absoluteOriginalPath),
                                $output,
                                $statusCode
                            );

                            if ($statusCode === 0) {
                                Notification::make()
                                    ->title('Printed Successfully')
                                    ->body('Original ADC sent to printer: ' . $printerName)
                                    ->success()
                                    ->send();

                                // Mark request as used
                                if ($record->is_request_original) {
                                    $record->update(['is_request_original' => false]);
                                }

                                $record->increment('print_count');

                                DB::table('print_logs')->insert([
                                    'user_id' => auth()->id(),
                                    'document_id' => $record->id,
                                    'copy_type' => 'ORIGINAL',
                                    'printer' => $printerName ?? 'NO_PRINTER_AVAILABLE',
                                    'created_at' => now(),
                                ]);
                            } else {
                                Notification::make()
                                    ->title('ADC Printing Failed')
                                    ->body('Please try to print again.')
                                    ->warning()
                                    ->send();

                                Log::error('ADC printing failed', [
                                    'soa_id' => $record->id,
                                    'printer' => $printerName,
                                    'output' => $output,
                                ]);
                            }
                        } else {
                            Notification::make()
                                ->title('No Printer Found')
                                ->body('No available printer for ADC ID ' . $record->id)
                                ->warning()
                                ->send();

                            Log::error('No available printer for ADC ID ' . $record->id);
                        }
                    })
                    ->visible(
                        fn(GeneratedSoa $record) =>
                        $record->request_status === 'APPROVED' &&
                            auth()->user()->can('generated_adc.print_original') &&
                            $record->is_request_original
                            && auth()->user()->hasAnyRole([Role::CLAIMS_PROCESSOR]),
                    ),
                // Download Duplicate
                Action::make('download_pdf')
                    ->label('Download Duplicate')
                    ->icon('heroicon-o-document-arrow-down')
                    ->button()
                    ->action(function (GeneratedSoa $record) {
                        $disk = Storage::disk('public');
                        if (!$disk->exists($record->duplicate_file_path)) {
                            Notification::make()
                                ->title('PDF file not found.')
                                ->body('No PDF file was found.')
                                ->warning()
                                ->send();
                            return;
                        }

                        return response()->download(
                            $disk->path($record->duplicate_file_path),
                            basename($record->duplicate_file_path)
                        );
                    }),

            ])
            ->filters([
                // ADC Status
                Tables\Filters\SelectFilter::make('status')
                    ->label('ADC Status')
                    ->options([
                        'PENDING'  => 'Pending',
                        'APPROVED' => 'Approved',
                        'REJECTED' => 'Rejected',
                    ]),

                // Clinic Filter
                Tables\Filters\SelectFilter::make('clinic_id')
                    ->label('Clinic')
                    ->relationship('clinic', 'clinic_name')
                    ->searchable()
                    ->preload(),

                Tables\Filters\SelectFilter::make('request_status')
                    ->label('Original Request Status')
                    ->options([
                        'PENDING'  => 'Pending',
                        'APPROVED' => 'Approved',
                        'REJECTED' => 'Rejected',
                    ]),

                // Date Range Filter
                Tables\Filters\Filter::make('created_at')
                    ->label('Generated Date')
                    ->form([
                        Forms\Components\DatePicker::make('from')->label('From'),
                        Forms\Components\DatePicker::make('until')->label('Until'),
                    ])
                    ->query(function ($query, array $data) {
                        return $query
                            ->when($data['from'], fn($q) =>
                            $q->whereDate('created_at', '>=', $data['from']))
                            ->when($data['until'], fn($q) =>
                            $q->whereDate('created_at', '<=', $data['until']));
                    }),
            ]);
    }
    public static function getNavigationBadge(): ?string
    {
        if (! auth()->user()?->hasAnyRole([
            Role::SUPER_ADMIN,
            Role::UPPER_MANAGEMENT,
            Role::MIDDLE_MANAGEMENT,
        ])) {
            return null;
        }

        $count = GeneratedSoa::where('request_status', 'PENDING')->count();
        return $count > 0 ? (string) $count : null;
    }

    public static function getNavigationBadgeColor(): ?string
    {
        return 'warning';
    }

    public static function shouldRegisterNavigation(): bool
    {
        return auth()->check()
            && auth()->user()->can('generated_adc.view');
    }
    public static function canViewAny(): bool
    {
        return auth()->user()->can('generated_adc.view');
    }
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListGeneratedSoas::route('/'),
        ];
    }
}
