<?php

namespace App\Filament\Resources;

use App\Filament\Resources\GeneratedSoaResource\Pages;
use App\Models\GeneratedSoa;
use App\Models\Procedure;
use App\Models\Role;
use App\Models\User;
use App\Services\PrinterService;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Resources\Resource;
use Filament\Tables\Actions\Action;
use Barryvdh\DomPDF\Facade\Pdf;
use Filament\Infolists\Components\Grid;
use Filament\Tables\Columns\TextColumn;
use Illuminate\Support\Facades\Storage;
use Filament\Notifications\Notification;
use Filament\Notifications\Actions\Action as NotificationAction;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class GeneratedSoaResource extends Resource
{
    protected static ?string $model = GeneratedSoa::class;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';
    protected static ?string $navigationGroup = 'Claims Management';
    protected static ?string $label = 'Generated ADC';


    // ✅ Table schema
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('id')
                    ->label('ADC Number')
                    ->getStateUsing(fn($record) => $record->procedures()->value('adc_number') ?? '—')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('clinic.clinic_name')
                    ->label('Clinic')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('from_date')->label('From')->date(),
                Tables\Columns\TextColumn::make('to_date')->label('To')->date(),
                Tables\Columns\TextColumn::make('total_amount')->label('Total')->money('php'),
                Tables\Columns\BadgeColumn::make('status')
                    ->label('ADC Status')
                    ->getStateUsing(fn($record) => $record->status ?? 'generated')
                    ->colors([
                        'warning'   => 'generated',
                        'info'      => 'printing',
                        'success'   => 'processed',
                        'danger'    => 'print_failed',
                    ])
                    ->icons([
                        'heroicon-o-clock'        => 'generated',
                        'heroicon-o-arrow-path'   => 'printing',
                        'heroicon-o-check-circle' => 'processed',
                        'heroicon-o-x-circle'     => 'print_failed',
                    ]),
                Tables\Columns\TextColumn::make('generatedBy.name')->label('Generated by'),
                Tables\Columns\TextColumn::make('created_at')->label('Generated At')->dateTime(),
                Tables\Columns\TextColumn::make('generatedBy.name')
                    ->label('Generated by')
                    ->searchable(),

                Tables\Columns\TextColumn::make('created_at')
                    ->label('Generated At')
                    ->dateTime()
                    ->sortable(),

                Tables\Columns\TextColumn::make('print_count')
                    ->label('Print Count'),

                Tables\Columns\BadgeColumn::make('request_status')
                    ->label('Original Request')
                    ->getStateUsing(fn($record) => $record->request_status ?? 'Not Requested')
                    ->colors([
                        'warning' => 'PENDING',
                        'success' => 'APPROVED',
                        'danger' => 'REJECTED',
                        'secondary' => 'Not Requested',
                    ])
            ])
            ->actions([

                // Request Original
                Action::make('request_original')
                    ->label('Request Original')
                    ->visible(auth()->user()->can('generated_adc.request'))
                    ->icon('heroicon-o-paper-airplane')
                    ->color('warning')
                    ->requiresConfirmation()
                    ->modalHeading('Request Original ADC')
                    ->modalDescription('Are you sure you want to request the original ADC? This will notify management for approval.')
                    ->modalSubmitActionLabel('Yes, Request')
                    ->action(function (GeneratedSoa $record) {
                        if ($record->request_status === 'PENDING' || $record->request_status === 'APPROVED') {
                            Notification::make()
                                ->title('Already requested or approved')
                                ->body('You cannot request again.')
                                ->warning()
                                ->send();
                            return;
                        }

                        $record->update([
                            'is_request_original' => true,
                            'request_status'      => 'PENDING',
                        ]);

                        // Notify upper management
                        $managers = User::role([Role::UPPER_MANAGEMENT, Role::MIDDLE_MANAGEMENT, Role::SUPER_ADMIN])->get();
                        $url = static::getUrl('index');
                        foreach ($managers as $manager) {
                            Notification::make()
                                ->title('Original ADC Requested')
                                ->body(auth()->user()->name . ' requested the original ADC for ' . ($record->clinic?->clinic_name ?? 'ADC #' . $record->id) . '.')
                                ->warning()
                                ->actions([NotificationAction::make('review')->label('Review')->url($url)])
                                ->sendToDatabase($manager);
                        }

                        Notification::make()
                            ->title('Request sent')
                            ->body('Your request for the original ADC has been submitted. Management has been notified.')
                            ->success()
                            ->send();
                    })
                    ->visible(fn(GeneratedSoa $record) => $record->request_status === null),

                // Approve Original (Admin only)
                Action::make('approve_original')
                    ->label('Approve Original')
                    ->visible(auth()->user()->can('generated_adc.approve'))
                    ->icon('heroicon-o-check-circle')
                    ->color('success')
                    ->requiresConfirmation()
                    ->modalHeading('Approve Original ADC')
                    ->modalDescription('This request has been approved. The Claims Management team can now print the original ADC. Note: This action is allowed only once.')
                    ->modalSubmitActionLabel('Yes, Approve')
                    ->action(function (GeneratedSoa $record) {
                        $record->update([
                            'request_status' => 'APPROVED',
                        ]);

                        // Notify claims processors
                        $claimsUsers = User::permission('generated_adc.print_original')->get();
                        $url = static::getUrl('index');
                        foreach ($claimsUsers as $user) {
                            Notification::make()
                                ->title('Original ADC Approved')
                                ->body('The original ADC request for ' . ($record->clinic?->clinic_name ?? 'ADC #' . $record->id) . ' has been approved. You can now print it.')
                                ->success()
                                ->actions([NotificationAction::make('print')->label('View ADC')->url($url)])
                                ->sendToDatabase($user);
                        }

                        Notification::make()
                            ->title('Approved')
                            ->body('Original ADC request has been approved. Claims team has been notified.')
                            ->success()
                            ->send();
                    })
                    ->visible(fn(GeneratedSoa $record) => $record->request_status === 'PENDING' && auth()->user()->can('generated_adc.approve')),

                // Print Original (Claims Processor only after approval)
                Action::make('print_original')
                    ->label('Print Original ADC')
                    ->icon('heroicon-o-printer')
                    ->color('success')
                    ->visible(
                        fn(GeneratedSoa $record) =>
                        $record->request_status === 'APPROVED' &&
                        $record->is_request_original &&
                        auth()->user()->can('generated_adc.print_original') &&
                        auth()->user()->hasAnyRole([Role::CLAIMS_PROCESSOR])
                    )
                    ->form(function (GeneratedSoa $record) {
                        $clinicPrinter = $record->clinic->printer_name ?? null;
                        $printers      = PrinterService::getAvailablePrinters();
                        $default       = PrinterService::getPrinter($clinicPrinter);

                        if (empty($printers)) {
                            return [
                                Forms\Components\TextInput::make('printer')
                                    ->label('Printer Name')
                                    ->placeholder('e.g. EPSON_L365_Series_8')
                                    ->required()
                                    ->helperText('No printers auto-detected. Enter the printer name manually.'),
                            ];
                        }

                        return [
                            Forms\Components\Select::make('printer')
                                ->label('Select Printer')
                                ->options(array_combine($printers, $printers))
                                ->default($default)
                                ->required()
                                ->helperText('Choose the printer to send this original ADC to.'),
                        ];
                    })
                    ->modalHeading('Print Original ADC')
                    ->modalSubmitActionLabel('Print Now')
                    ->action(function (GeneratedSoa $record, array $data) {
                        $disk        = Storage::disk('public');
                        $printerName = $data['printer'] ?? null;

                        if (!$printerName) {
                            Notification::make()->warning()->title('No printer selected.')->send();
                            return;
                        }

                        if (!$disk->exists($record->file_path)) {
                            Notification::make()->warning()->title('PDF not found')->body('Original ADC PDF file is missing.')->send();
                            return;
                        }

                        if (!PrinterService::isPrinterOnline($printerName)) {
                            Notification::make()->danger()->title('Printer Offline')->body("'{$printerName}' is currently offline. Please check the printer and try again.")->send();
                            return;
                        }

                        $absolutePath = $disk->path($record->file_path);
                        $output       = [];
                        exec(
                            'lp -o landscape -d ' . escapeshellarg($printerName) . ' ' . escapeshellarg($absolutePath) . ' 2>&1',
                            $output,
                            $statusCode
                        );

                        if ($statusCode !== 0) {
                            Notification::make()->warning()->title('Print Failed')->body('The print job was rejected by the printer. Please try again.')->send();
                            Log::error('Original ADC printing failed', ['soa_id' => $record->id, 'printer' => $printerName, 'output' => $output]);
                            return;
                        }

                        // Extract CUPS job ID
                        $jobId = null;
                        foreach ($output as $line) {
                            if (preg_match('/request id is (\S+)/i', $line, $matches)) {
                                $jobId = $matches[1];
                                break;
                            }
                        }

                        $record->update(['is_request_original' => false]);
                        $record->increment('print_count');

                        if (\App\Filament\Pages\PrinterSettings::isSimulating()) {
                            $record->update(['status' => 'processed']);
                            Procedure::whereIn('id', $record->procedures->pluck('id'))->update(['status' => 'processed']);
                            DB::table('print_logs')->insert([
                                'user_id'     => auth()->id(),
                                'document_id' => $record->id,
                                'copy_type'   => 'ORIGINAL',
                                'printer'     => 'SIMULATED',
                                'cups_job_id' => null,
                                'status'      => 'completed',
                                'created_at'  => now(),
                            ]);
                            Notification::make()->success()->title('ADC Processed (Simulated)')->body('Print simulation enabled — claims marked as processed.')->send();
                            return;
                        }

                        if (!PrinterService::isPrinterOnline($printerName)) {
                            Notification::make()->danger()->title('Printer Offline')->body("'{$printerName}' is currently offline. Please check the printer and try again.")->send();
                            return;
                        }

                        $absolutePath = $disk->path($record->file_path);
                        $output       = [];
                        exec(
                            'lp -o landscape -d ' . escapeshellarg($printerName) . ' ' . escapeshellarg($absolutePath) . ' 2>&1',
                            $output,
                            $statusCode
                        );

                        if ($statusCode !== 0) {
                            Notification::make()->warning()->title('Print Failed')->body('The print job was rejected by the printer. Please try again.')->send();
                            Log::error('Original ADC printing failed', ['soa_id' => $record->id, 'printer' => $printerName, 'output' => $output]);
                            return;
                        }

                        $jobId = null;
                        foreach ($output as $line) {
                            if (preg_match('/request id is (\S+)/i', $line, $matches)) {
                                $jobId = $matches[1];
                                break;
                            }
                        }

                        DB::table('print_logs')->insert([
                            'user_id'     => auth()->id(),
                            'document_id' => $record->id,
                            'copy_type'   => 'ORIGINAL',
                            'printer'     => $printerName,
                            'cups_job_id' => $jobId,
                            'status'      => 'sent',
                            'created_at'  => now(),
                        ]);

                        Notification::make()->success()->title('Original ADC Sent to Printer')->body('Document sent to ' . $printerName . '.')->send();
                    }),
                // Download Duplicate
                Action::make('download_pdf')
                    ->label('Download Duplicate')
                    ->icon('heroicon-o-document-arrow-down')
                    ->button()
                    ->action(function (GeneratedSoa $record) {
                        $disk = Storage::disk('public');
                        if (!$disk->exists($record->duplicate_file_path)) {
                            Notification::make()
                                ->title('PDF file not found.')
                                ->body('No PDF file was found.')
                                ->warning()
                                ->send();
                            return;
                        }

                        return response()->download(
                            $disk->path($record->duplicate_file_path),
                            basename($record->duplicate_file_path)
                        );
                    }),

            ])
            ->filters([
                // ADC Status
                Tables\Filters\SelectFilter::make('status')
                    ->label('ADC Status')
                    ->options([
                        'PENDING'  => 'Pending',
                        'APPROVED' => 'Approved',
                        'REJECTED' => 'Rejected',
                    ]),

                // Clinic Filter
                Tables\Filters\SelectFilter::make('clinic_id')
                    ->label('Clinic')
                    ->relationship('clinic', 'clinic_name')
                    ->searchable()
                    ->preload(),

                Tables\Filters\SelectFilter::make('request_status')
                    ->label('Original Request Status')
                    ->options([
                        'PENDING'  => 'Pending',
                        'APPROVED' => 'Approved',
                        'REJECTED' => 'Rejected',
                    ]),

                // Date Range Filter
                Tables\Filters\Filter::make('created_at')
                    ->label('Generated Date')
                    ->form([
                        Forms\Components\DatePicker::make('from')->label('From'),
                        Forms\Components\DatePicker::make('until')->label('Until'),
                    ])
                    ->query(function ($query, array $data) {
                        return $query
                            ->when($data['from'], fn($q) =>
                            $q->whereDate('created_at', '>=', $data['from']))
                            ->when($data['until'], fn($q) =>
                            $q->whereDate('created_at', '<=', $data['until']));
                    }),
            ]);
    }
    public static function getNavigationBadge(): ?string
    {
        if (! auth()->user()?->hasAnyRole([
            Role::SUPER_ADMIN,
            Role::UPPER_MANAGEMENT,
            Role::MIDDLE_MANAGEMENT,
        ])) {
            return null;
        }

        $count = GeneratedSoa::where('request_status', 'PENDING')->count();
        return $count > 0 ? (string) $count : null;
    }

    public static function getNavigationBadgeColor(): ?string
    {
        return 'warning';
    }

    public static function shouldRegisterNavigation(): bool
    {
        return auth()->check()
            && auth()->user()->can('generated_adc.view');
    }
    public static function canViewAny(): bool
    {
        return auth()->user()->can('generated_adc.view');
    }
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListGeneratedSoas::route('/'),
        ];
    }
}
